### ISSUE TITLE
Write about implementing testing

### ISSUE THREAD

**Issue by marianntlu** [TLU-Human-computer-interaction/masterThesis#21]
GanttStart: 2022-08-01
GanttDue: 2022-10-01

**Comment by marianntapfer** [comment]
Read about continuous

[2022_state_of_devops_report.pdf](https://github.com/marianntapfer/masterThesis/files/9949589/2022_state_of_devops_report.pdf)

 delivery here: 
Search for testing and Page: 32

Continuous delivery (CD) is a software development practice that:
1. Enables the team to deploy software to production or end users at any time
2. Ensures the software is in a deployable state throughout its lifecycle, including when working on new features
3. Establishes a fast feedback loop that enables the team to check the quality and deployability of the system, and prioritizes fixing issues blocking deployment.

Page 60 has a question about disability - 11% - pretty high

**Comment by marianntapfer** [comment]
https://blog.diamond.la/how-to-automate-accessibility-tests-with-cypress
